#!/bin/sh
# Using external pipe with st, give a rofi prompt of recent commands,
# allowing the user to copy the output of one.
# xclip/xsel required for this script.

# Create a tempfile to store the output
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)

trap 'rm "$tmpfile"' 0 1 15

sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"

ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"

chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -dmenu -i -p "Copy which command's output?" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"

eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"

to_copy="$(awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | head -n -"$(($2 - 1))")"

# copy it to the clipboard
echo "$to_copy" | xclip -selection clipboard
