#!/bin/sh

urlregex="(((http|https|gopher|gemini|ftp|ftps|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

# First remove linebreaks and mutt sidebars
urls="$(sed 's/.*│//g' | tr -d '\n')"
# grep only urls as defined above and get the unique ones
urls="$(echo "$urls" | grep -aEo "$urlregex" | uniq)"
# xdg-open will not detect url without http
urls="$(echo "$urls" | sed 's/\(\.\|,\|;\|\!\\|\?\)$//; s/^www./http:\/\/www\./')"

[ -z "$urls" ] && exit 1

while getopts "hoc" o; do
	case "${o}" in
		h) printf 'Optional arguments for custom use:\n  -c: copy\n  -o: xdg-open\n  -h: Show this message\n' && exit 1 ;;
		c) echo "$urls" | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -dmenu -i -p "Copy which url?" | tr -d '\n' | xclip -selection clipboard ;;
		*) printf 'Invalid option: -%s\n' "$OPTARG" && exit 1 ;;
	esac
done
